CREATE DATABASE QUANLY_BEAUTY_HEALTH
ON ( NAME = 'QUANLYBH_DATA', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.MDF')
LOG ON ( NAME = 'QUANLYBH_LOG', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.LDF')
GO

USE QUANLY_BEAUTY_HEALTH
GO

CREATE TABLE LOAITAIKHOAN
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
GO
DROP TABLE dbo.TAIKHOAN
CREATE TABLE TAIKHOAN 
(
	TAIKHOAN NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(100) NOT NULL CHECK (LEN(MATKHAU) >=8),
	TENTAIKHOAN NVARCHAR(50) NOT NULL,
	MALOAI INT NOT NULL
	FOREIGN KEY (MALOAI) REFERENCES dbo.LOAITAIKHOAN(MALOAI)
)
ALTER TABLE dbo.TAIKHOAN ADD EMAIL VARCHAR(50);
ALTER TABLE dbo.TAIKHOAN ADD CONSTRAINT CONSTRAIN_EMAIL UNIQUE (EMAIL);
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)

GO
DROP TABLE dbo.KHACHHANG

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50) NOT NULL, 
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE KHO
(
	MAKHO VARCHAR(10) PRIMARY KEY,
	TENKHO NVARCHAR(50), 
	DIACHI NVARCHAR(100),
)
GO
CREATE TABLE DANHMUC
(
	MADM VARCHAR(10) PRIMARY KEY,
	TENDM NVARCHAR(100)
)
GO
CREATE TABLE LOAISANPHAM
(
	MALOAI VARCHAR(10) PRIMARY KEY,
	TENLOAI NVARCHAR(50),
	MADM VARCHAR(10)
	FOREIGN KEY (MADM) REFERENCES dbo.DANHMUC(MADM)
)
GO
CREATE TABLE SANPHAM 
(
	MASP VARCHAR(10) PRIMARY KEY, 
	TENSP NVARCHAR(10) NOT NULL,
	GIATIEN MONEY CHECK (GIATIEN > 0 ),
	DONVITINH NVARCHAR(10),
	HANSUDUNG DATETIME,
	MAKHO VARCHAR(10), 
	SOLUONGTON INT CHECK (SOLUONGTON >= 0),
	FOREIGN KEY (MAKHO) REFERENCES dbo.KHO (MAKHO)
)
GO
CREATE TABLE HOADON 
(
	MAHD VARCHAR(10) PRIMARY KEY,
	MANV VARCHAR(10),
	MAKH VARCHAR(10), 
	NGAYLAP DATE,
	KHUYENMAI FLOAT DEFAULT 0,
	THANHTIEN MONEY,
	TRANGTHAI NVARCHAR(20)
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH)
)
ALTER TABLE dbo.HOADON ADD CONSTRAINT TRANGTHAI_CONSTRAIN DEFAULT N'CHƯA THANH TOÁN' FOR TRANGTHAI
ALTER TABLE dbo.HOADON ADD KHUYENMAI FLOAT
GO
CREATE TABLE PHIEUGIAOHANG
(
	MAPGH VARCHAR(10) PRIMARY KEY,
	MANCC VARCHAR(10),
	MANV VARCHAR(10), 
	FOREIGN KEY (MANCC) REFERENCES dbo.NHACUNGCAP(MANCC),
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
)
GO
CREATE TABLE CTPGH 
(
	MAPGH VARCHAR(10),
	MASP VARCHAR(10),
	HANSUDUNG DATE,
	PRIMARY KEY(MAPGH,MASP),
	NGAYDAT DATE,
	NGAYNHAN DATE CHECK (NGAYNHAN >= NGAYDAT),
	SOLUONG INT,
	TONGTIEN MONEY
	FOREIGN KEY (MAPGH) REFERENCES dbo.PHIEUGIAOHANG (MAPGH),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM (MASP),
)
ALTER TABLE dbo.CTPGH ADD HANSUDUNG DATE
GO

CREATE TABLE GIOHANG
(
	MAHD VARCHAR(10),
	MASP VARCHAR(10),
	PRIMARY KEY (MAHD, MASP),
	SOLUONG INT CHECK (SOLUONG > 0),
	GIABAN MONEY,
	FOREIGN KEY (MAHD) REFERENCES dbo.HOADON(MAHD),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO
ALTER TABLE dbo.GIOHANG ADD GIABAN MONEY
GO

--select EncryptedData = EncryptByPassPhrase('123', 'laptrinhvb.net' )
--select EncryptedData = EncryptByPassPhrase('123', 'ADMIN1234' )
--SELECT * FROM dbo.TAIKHOAN
--UPDATE dbo.TAIKHOAN
--SET MATKHAU = (select EncryptedData = EncryptByPassPhrase('123', 'ADMIN1234' ))
--WHERE TAIKHOAN = 'ADMIN'

--select convert(varchar(100),DecryptByPassPhrase('123', 0x02000000107A7025546B1299EA4C9BB78B6CDC13C7A214905A930AD07424825E17F3770D157A016CA78AD830EA4E41C4AD1BF8AF)) as giaima
--FROM dbo.TAIKHOAN WHERE dbo.TAIKHOAN = 'admin'

--INSERT INTO dbo.TAIKHOAN
--(
--    TAIKHOAN,
--    MATKHAU,
--    TENTAIKHOAN,
--    MALOAI
--)
--VALUES
--(   N'NGHIAXX', -- TAIKHOAN - nvarchar(50)
--    EncryptByPassPhrase('123', 'ADMIN1234' ), -- MATKHAU - nvarchar(50)
--    N'VAN NGHIA', -- TENTAIKHOAN - nvarchar(50)
--    1    -- MALOAI - int
--    )
--GO
--SELECT * FROM dbo.HOADON WHERE THANHTIEN > 300.000
--SELECT 
--FROM dbo.GIOHANG, dbo.HOADON
--WHERE HD.MAHD = dbo.GIOHANG.MAHD


--SELECT COUNT(SOLUONG), MASP
--FROM dbo.HOADON HD, dbo.GIOHANG
--WHERE HD.MAHD = dbo.GIOHANG.MAHD
--GROUP BY MASP

----SELECT (SP.SOLUONGTON - GH.SOLUONG)
----FROM dbo.SANPHAM SP, dbo.GIOHANG GH, dbo.HOADON HD
----WHERE SP.MASP = GH.MASP AND GH.MAHD = HD.MAHD AND HD.M


--CREATE VIEW BAOMATTAIKHOAN
--AS
--	SELECT * FROM dbo.HOADON, dbo.GIOHANG
--	WHERE dbo.GIOHANG.MAHD = dbo.HOADON.MAHD

--SELECT * FROM BAOMATTAIKHOAN
--SELEC

--- Proc xóa sản phẩm
CREATE PROC DELETE_SP @MASP VARCHAR(10)
AS
BEGIN
	DELETE FROM dbo.SANPHAM WHERE MASP = @MASP
END

EXEC dbo.DELETE_SP @MASP = 'SP20' -- varchar(10)
 
 DELETE FROM dbo.KHACHHANG WHERE MAKH = 'KH15'
 DELETE FROM dbo.TAIKHOAN WHERE TAIKHOAN = 'taikhoan1'

 ALTER TABLE dbo.HOADON
 ADD CONSTRAINT FK_KHHD
 FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH) ON DELETE SET NULL;

 -- Check valid Login
CREATE OR ALTER PROC CHECK_LOGIN @USERNAME NVARCHAR(50), @PASS NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 1)
		SELECT 1 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 2)
		SELECT 2 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU != @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  )
		SELECT 3 AS CODE
	ELSE
		SELECT 4 AS CODE
END

EXEC CHECK_LOGIN 'ADMIN', 'ADMIN1234'

-- Lấy sản phẩm
CREATE PROC GET_PRODUCT
AS 
BEGIN
	SELECT MASP, TENSP, GIATIEN, DONVITINH, SOLUONGTON, TENKHO FROM dbo.SANPHAM, dbo.KHO WHERE dbo.SANPHAM.MAKHO = dbo.KHO.MAKHO

END
EXEC GET_PRODUCT

----- Insert Hóa đơn 
CREATE OR ALTER PROC INSERT_HOADONByGioHang @MAHD VARCHAR(10), @MANV VARCHAR(10), 
@MAKH VARCHAR(10), @NGAYLAP DATE, @KHUYENMAI INT, @THANHTIEN MONEY
AS
BEGIN
	INSERT INTO dbo.HOADON
	(
	    MAHD,
	    MANV,
	    MAKH,
	    NGAYLAP,
	    THANHTIEN,
	    KHUYENMAI
	)
	VALUES
	(   @MAHD,        -- MAHD - varchar(10)
	    @MANV,        -- MANV - varchar(10)
	    @MAKH,        -- MAKH - varchar(10)
	    @NGAYLAP, -- NGAYLAP - date
	    @THANHTIEN,      -- THANHTIEN - money
	    @KHUYENMAI       -- KHUYENMAI - float
	    )
END
EXEC dbo.INSERT_HOADONByGioHang @MAHD = 'HDA34342A4',              -- varchar(10)
                       @MANV = 'NV01',              -- varchar(10)
                       @MAKH = 'KH01',              -- varchar(10)
                       @NGAYLAP = '', -- date
                       @KHUYENMAI = 10,          -- int
                       @THANHTIEN = 50000000      -- money

-- insert  Giỏ hàng
CREATE or alter PROC INSERT_GIOHANG @MAHD VARCHAR(10), @MASP VARCHAR(10), @SOLUONG INT
AS
BEGIN
	INSERT INTO dbo.GIOHANG
	(
	    MAHD,
	    MASP,
	    SOLUONG
	)
	VALUES
	(   @MAHD,  -- MAHD - varchar(10)
	    @MASP,  -- MASP - varchar(10)
	    @SOLUONG  -- SOLUONG - int
	    )
END

EXEC INSERT_GIOHANG '008F2FBK', 'SP03', 20
EXEC dbo.INSERT_GIOHANG @MAHD = 'HD11',    -- varchar(10)
                        @MASP = 'SP11',    -- varchar(10)
                        @SOLUONG = 10,  -- int
                        @GIABAN = 500000 -- money

GO
------ cập nhật trạng thái thanh toán
CREATE PROC UPDATE_TRANGTHAI @MAHD VARCHAR(10)
AS
BEGIN
	UPDATE dbo.HOADON SET TRANGTHAI = N'ĐÃ THANH TOÁN' WHERE MAHD = @MAHD

END
EXEC dbo.UPDATE_TRANGTHAI @MAHD = '5ZEGIG1N' -- varchar(10)
--
CREATE VIEW HD_KMAI
AS
SELECT HD.MAHD, HD.KHUYENMAI*HD.THANHTIEN KHUYENMAI				
FROM HOADON HD
SELECT * FROM HD_KMAI
---
SELECT SP.TENSP, SP.HANSUDUNG, GH.SOLUONG, GH.GIABAN, TENKH, SDT
FROM dbo.HOADON HD, dbo.SANPHAM SP, dbo.GIOHANG GH, KHACHHANG kh
WHERE HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP and hd.MAKH = kh.MAKH


-- THÔNG TIN HÓA ĐƠN BÁN HÀNG
GO
CREATE OR ALTER PROC GET_INF_INVOICE @MAHD VARCHAR(10)
AS
BEGIN
	SELECT SP.TENSP, SP.HANSUDUNG, GH.SOLUONG, GH.GIABAN,HD.MAHD,HD.KHUYENMAI, KH.TENKH, SDT, HD.THANHTIEN
	FROM dbo.HOADON HD, dbo.SANPHAM SP, dbo.GIOHANG GH, KHACHHANG KH
	WHERE HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP AND HD.MAHD = @MAHD AND KH.MAKH = HD.MAKH 
END
GO
EXEC GET_INF_INVOICE 'HD01'
--- update giaban giohang
--UPDATE GIOHANG
--SET GIABAN = SOLUONG * SP.GIATIEN
--FROM SANPHAM SP
--WHERE SP.MASP = GIOHANG.MASP 

--- UPDATE THANH TIEN HOA DON
--UPDATE HOADON
--SET THANHTIEN = (SELECT SUM(GIABAN) FROM GIOHANG GH WHERE GH.MAHD = HOADON.MAHD)
--WHERE SP.MASP = GIOHANG.MASP 
--- THỐNG KÊ DOANH THU 
GO
CREATE OR ALTER PROC TKDT_NAM
AS
BEGIN
SELECT SUM(THANHTIEN) DOANHTHU, MONTH(NGAYLAP) THANG
FROM dbo.HOADON 
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12
GROUP BY MONTH(NGAYLAP)
ORDER BY THANG
END
GO
EXEC TKDT_NAM
--- data doanh thu khách hàng SP
GO
CREATE OR ALTER PROC doanhThuData
AS
BEGIN
SELECT MONTH(NGAYLAP) THANG, SP.MASP, SP.TENSP, SUM(GH.SOLUONG) SOLUONGBAN ,SUM(GH.GIABAN) DOANHTHU
FROM dbo.HOADON HD, SANPHAM SP, GIOHANG GH
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12 AND HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP
GROUP BY MONTH(NGAYLAP),SP.TENSP, SP.MASP
ORDER BY THANG
END
GO
exec doanhThuData
--- TK SLUONG HÓA ĐƠN
GO
CREATE OR ALTER PROC TKSLHD
AS
BEGIN
SELECT COUNT(*) SOLUONGHD, MONTH(NGAYLAP) THANG
FROM dbo.HOADON
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12
GROUP BY MONTH(NGAYLAP) 
END
GO
EXEC TKSLHD
--- TK SAN PHAM
GO
CREATE OR ALTER PROC TKSP
AS
BEGIN
SELECT SUM(GH.SOLUONG) TONGSOLUONG, SP.MASP
FROM SANPHAM SP, GIOHANG GH
WHERE GH.MASP = SP.MASP 
GROUP BY SP.MASP
END
GO
EXEC TKSP
GO
--- LAY DANH MUC THEO TEN
GO
CREATE or ALTER PROC GET_DANHMUC @TENDM NVARCHAR(100)
AS
BEGIN
	SELECT SP.MASP, SP.TENSP, SP.DONVITINH, SP.HANSUDUNG, SP.SOLUONGTON, SP.MAKHO, SP.MALOAI
	FROM SANPHAM SP, LOAISANPHAM L, DANHMUC DM
	WHERE SP.MALOAI = L.MALOAI AND L.MADM = DM.MADM AND DM.TENDANHMUC LIKE @TENDM
END
GO
EXEC GET_DANHMUC N'Tăng cường miễn dịch'

select * from taikhoan


GO
GO

CREATE PROC UPDATE_MK @MATKHAUMOI NVARCHAR(100), @EMAIL varchar(50)
AS
BEGIN
update TAIKHOAN 
set MATKHAU = @MATKHAUMOI
WHERE EMAIL = @EMAIL
END

GO
EXEC UPDATE_MK 'Nghia123', 'vantoan12@gmail.com'


ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ON DELETE CASCADE

ALTER TABLE GIOHANG ADD CONSTRAINT FK_HD_GH FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD) ON DELETE CASCADE


EXEC HIENTHI_CTHD 'HD01'
SELECT * FROM HOADON
GO
CREATE PROC GETDATA_HD @MAHD VARCHAR(10)
AS
BEGIN
	SELECT TENKH, TENNV, NGAYLAP, THANHTIEN, HD.MAHD
	FROM HOADON HD, NHANVIEN NV, KHACHHANG KH
	WHERE HD.MANV = NV.MANV AND HD.MAKH = KH.MAKH AND HD.MAHD = @MAHD
END
GO
EXEC TKDT_NAM 

-- TOP 5 KH CO SO HOA DON ...
CREATE PROC GET_TOP5KH 
AS
BEGIN
SELECT TOP 5 KH.MAKH, SUM (GH.GIABAN) DOANHTHU
FROM KHACHHANG KH, GIOHANG GH, HOADON HD
WHERE HD.MAHD = GH.MAHD AND HD.MAKH = KH.MAKH 
GROUP BY KH.MAKH
ORDER BY SUM(GH.GIABAN) DESC
END


-- TRIGGER CẬP NHẬT SỐ LƯỢNG TỒN KHI MUA HÀNG
GO
CREATE or alter TRIGGER CAPNHATSLTON 
ON dbo.GIOHANG
FOR INSERT
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT
	SELECT @MASP = Inserted.MASP, @SOLUONG = Inserted.SOLUONG  FROM Inserted
	UPDATE dbo.SANPHAM 
	SET SOLUONGTON = SOLUONGTON - @SOLUONG
	WHERE dbo.SANPHAM.MASP = @MASP
END
insert into GIOHANG values ('008F2FBK', 'SP05', 10, 5000 )
GO
--UPDATE GIÁ BÁN GIỎ HÀNG
UPDATE dbo.GIOHANG 
SET GIABAN = SP.GIATIEN * SOLUONG
FROM dbo.SANPHAM SP
WHERE SP.MASP = dbo.GIOHANG.MASP
-- TRIGGER TÍNH GIÁ BÁN CỦA GIỎ HÀNG
CREATE OR ALTER TRIGGER CAL_GIABAN
ON dbo.GIOHANG
FOR INSERT
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT , @HOADON VARCHAR(10)
	SELECT @MASP = I.MASP, @SOLUONG = I.SOLUONG, @HOADON = I.MAHD FROM INSERTED I
	UPDATE dbo.GIOHANG
	SET GIABAN = @SOLUONG * SP.GIATIEN
	FROM SANPHAM SP
	WHERE SP.MASP = @MASP AND dbo.GIOHANG.MAHD = @HOADON AND GIOHANG.MASP = @MASP
END
GO
--- UPDATE TONG GIA SP CUA PHIEU GIAO HANG
UPDATE dbo.CTPGH
SET TONGTIEN = (SP.GIATIEN * SOLUONG)
FROM dbo.SANPHAM SP
WHERE SP.MASP = dbo.CTPGH.MASP

GO
-- TRIGGER CẬP NHẬT SỐ LƯỢNG KHI NHẬP HÀNG
CREATE TRIGGER UPDATE_NHAPHANG 
ON CTPGH
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT
	SELECT @MASP = I.MASP, @SOLUONG = I.SOLUONG FROM INSERTED I
	UPDATE dbo.SANPHAM
	SET SOLUONGTON = SOLUONGTON + @SOLUONG
	WHERE @MASP = dbo.SANPHAM.MASP
END

-- TRIGGER NHAP NHAT HAN SU DUNG CUA SAN PHAM KHI NHAP HANG
GO
CREATE TRIGGER UPDATE_HSD
ON dbo.CTPGH
FOR INSERT
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @HANSUDUNG DATE
	SELECT @MASP = I.MASP, @HANSUDUNG = I.HANSUDUNG FROM Inserted I
	UPDATE dbo.SANPHAM
	SET HANSUDUNG = @HANSUDUNG
	WHERE @MASP = dbo.SANPHAM.MASP
END
ALTER TABLE dbo.PHIEUGIAOHANG ADD MAKHO VARCHAR(10) 
ALTER TABLE dbo.PHIEUGIAOHANG ADD CONSTRAINT MAKHO_CT FOREIGN KEY (MAKHO) REFERENCES dbo.KHO (MAKHO)
GO


---
CREATE PROC DELETE_SP @MASP VARCHAR(10)
AS
BEGIN
	DELETE FROM dbo.SANPHAM WHERE MASP = @MASP
END

EXEC dbo.DELETE_SP @MASP = 'SP20' -- varchar(10)
 
 DELETE FROM dbo.KHACHHANG WHERE MAKH = 'KH15'
 DELETE FROM dbo.TAIKHOAN WHERE TAIKHOAN = 'taikhoan1'

 ALTER TABLE dbo.HOADON
 ADD CONSTRAINT FK_KHHD
 FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH) ON DELETE SET NULL;