CREATE DATABASE QUANLY_BEAUTY_HEALTH
ON ( NAME = 'QUANLYBH_DATA', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.MDF')
LOG ON ( NAME = 'QUANLYBH_LOG', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.LDF')
GO

USE QUANLY_BEAUTY_HEALTH
GO

CREATE TABLE LOAITAIKHOAN
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
GO
CREATE TABLE TAIKHOAN 
(
	TAIKHOAN NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL CHECK (LEN(MATKHAU) >=8),
	TENTAIKHOAN NVARCHAR(50) NOT NULL,
	MALOAI INT NOT NULL
	FOREIGN KEY (MALOAI) REFERENCES dbo.LOAITAIKHOAN(MALOAI)
)
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)

GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50) NOT NULL, 
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE KHO
(
	MAKHO VARCHAR(10) PRIMARY KEY,
	TENKHO NVARCHAR(50), 
	DIACHI NVARCHAR(100),
)
GO
CREATE TABLE SANPHAM 
(
	MASP VARCHAR(10) PRIMARY KEY, 
	TENSP NVARCHAR(10) NOT NULL,
	GIATIEN MONEY CHECK (GIATIEN > 0 ),
	DONVITINH NVARCHAR(10),
	HANSUDUNG DATETIME,
	MAKHO VARCHAR(10), 
	SOLUONGTON INT CHECK (SOLUONGTON >= 0),
	FOREIGN KEY (MAKHO) REFERENCES dbo.KHO (MAKHO)
)
GO
CREATE TABLE HOADON 
(
	MAHD VARCHAR(10) PRIMARY KEY,
	MANV VARCHAR(10),
	MAKH VARCHAR(10), 
	NGAYLAP DATE CHECK (NGAYLAP < GETDATE()),
	KHUYENMAI FLOAT,
	THANHTIEN MONEY,
	TRANGTHAI NVARCHAR(20)
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH)
)
ALTER TABLE dbo.HOADON ADD KHUYENMAI FLOAT
GO
CREATE TABLE PHIEUGIAOHANG
(
	MAPGH VARCHAR(10) PRIMARY KEY,
	MANCC VARCHAR(10),
	MANV VARCHAR(10), 
	FOREIGN KEY (MANCC) REFERENCES dbo.NHACUNGCAP(MANCC),
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
)
GO
CREATE TABLE CTPGH 
(
	MAPGH VARCHAR(10),
	MASP VARCHAR(10),
	HANSUDUNG DATE,
	PRIMARY KEY(MAPGH,MASP),
	NGAYDAT DATE,
	NGAYNHAN DATE CHECK (NGAYNHAN >= NGAYDAT),
	SOLUONG INT,
	TONGTIEN MONEY
	FOREIGN KEY (MAPGH) REFERENCES dbo.PHIEUGIAOHANG (MAPGH),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM (MASP),
)
ALTER TABLE dbo.CTPGH ADD HANSUDUNG DATE
GO
CREATE TABLE GIOHANG
(
	MAHD VARCHAR(10),
	MASP VARCHAR(10),
	PRIMARY KEY (MAHD, MASP),
	SOLUONG INT CHECK (SOLUONG > 0),
	GIABAN MONEY,
	FOREIGN KEY (MAHD) REFERENCES dbo.HOADON(MAHD),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP)
)
ALTER TABLE dbo.GIOHANG ADD GIABAN MONEY
GO

--sfsdfsdfsfsdf
CREATE PROC CHECK_LOGIN @USERNAME NVARCHAR(50), @PASS NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS AND MALOAI = 1)
		SELECT 1 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS AND MALOAI = 2)
		SELECT 2 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU != @PASS )
		SELECT 3 AS CODE
	ELSE
		SELECT 4 AS CODE


END
GO