CREATE DATABASE QUANLY_BEAUTY_HEALTH
ON ( NAME = 'QUANLYBH_DATA', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.MDF')
LOG ON ( NAME = 'QUANLYBH_LOG', FILENAME = 'C:\Users\Van Nghia\OneDrive\Desktop\Winform c#\DATA\QUANLYBH.LDF')
GO

USE QUANLY_BEAUTY_HEALTH
GO

CREATE TABLE LOAITAIKHOAN
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
GO
DROP TABLE dbo.TAIKHOAN
CREATE TABLE TAIKHOAN 
(
	TAIKHOAN NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(100) NOT NULL CHECK (LEN(MATKHAU) >=8),
	TENTAIKHOAN NVARCHAR(50) NOT NULL,
	MALOAI INT NOT NULL
	FOREIGN KEY (MALOAI) REFERENCES dbo.LOAITAIKHOAN(MALOAI)
)
ALTER TABLE dbo.TAIKHOAN ADD EMAIL VARCHAR(50);
ALTER TABLE dbo.TAIKHOAN ADD CONSTRAINT CONSTRAIN_EMAIL UNIQUE (EMAIL);
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)

GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50) NOT NULL, 
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(10) PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL,
	SDT VARCHAR(20) CHECK (LEN(SDT) >=10 AND LEN(SDT) <= 11),
	DIACHI NVARCHAR(100)
)
GO
CREATE TABLE KHO
(
	MAKHO VARCHAR(10) PRIMARY KEY,
	TENKHO NVARCHAR(50), 
	DIACHI NVARCHAR(100),
)
GO
CREATE TABLE DANHMUC
(
	MADM VARCHAR(10) PRIMARY KEY,
	TENDM NVARCHAR(100)
)
GO
CREATE TABLE LOAISANPHAM
(
	MALOAI VARCHAR(10) PRIMARY KEY,
	TENLOAI NVARCHAR(50),
	MADM VARCHAR(10)
	FOREIGN KEY (MADM) REFERENCES dbo.DANHMUC(MADM)
)
GO
CREATE TABLE SANPHAM 
(
	MASP VARCHAR(10) PRIMARY KEY, 
	TENSP NVARCHAR(10) NOT NULL,
	GIATIEN MONEY CHECK (GIATIEN > 0 ),
	DONVITINH NVARCHAR(10),
	HANSUDUNG DATETIME,
	MAKHO VARCHAR(10), 
	SOLUONGTON INT CHECK (SOLUONGTON >= 0),
	FOREIGN KEY (MAKHO) REFERENCES dbo.KHO (MAKHO)
)
GO
CREATE TABLE HOADON 
(
	MAHD VARCHAR(10) PRIMARY KEY,
	MANV VARCHAR(10),
	MAKH VARCHAR(10), 
	NGAYLAP DATE,
	KHUYENMAI FLOAT DEFAULT 0,
	THANHTIEN MONEY,
	TRANGTHAI NVARCHAR(20)
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH)
)
ALTER TABLE dbo.HOADON ADD CONSTRAINT TRANGTHAI_CONSTRAIN DEFAULT N'CHƯA THANH TOÁN' FOR TRANGTHAI
ALTER TABLE dbo.HOADON ADD KHUYENMAI FLOAT
GO
CREATE TABLE PHIEUGIAOHANG
(
	MAPGH VARCHAR(10) PRIMARY KEY,
	MANCC VARCHAR(10),
	MANV VARCHAR(10), 
	FOREIGN KEY (MANCC) REFERENCES dbo.NHACUNGCAP(MANCC),
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
)
GO
CREATE TABLE CTPGH 
(
	MAPGH VARCHAR(10),
	MASP VARCHAR(10),
	HANSUDUNG DATE,
	PRIMARY KEY(MAPGH,MASP),
	NGAYDAT DATE,
	NGAYNHAN DATE CHECK (NGAYNHAN >= NGAYDAT),
	SOLUONG INT,
	TONGTIEN MONEY
	FOREIGN KEY (MAPGH) REFERENCES dbo.PHIEUGIAOHANG (MAPGH),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM (MASP),
)
ALTER TABLE dbo.CTPGH ADD HANSUDUNG DATE
GO

CREATE TABLE GIOHANG
(
	MAHD VARCHAR(10),
	MASP VARCHAR(10),
	PRIMARY KEY (MAHD, MASP),
	SOLUONG INT CHECK (SOLUONG > 0),
	GIABAN MONEY,
	FOREIGN KEY (MAHD) REFERENCES dbo.HOADON(MAHD),
	FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP)
)
ALTER TABLE dbo.GIOHANG ADD GIABAN MONEY
GO

--sfsdfsdfsfsdf
CREATE OR ALTER PROC CHECK_LOGIN @USERNAME NVARCHAR(50), @PASS NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 1)
		SELECT 1 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 2)
		SELECT 2 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU != @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  )
		SELECT 3 AS CODE
	ELSE
		SELECT 4 AS CODE
END

EXEC CHECK_LOGIN 'ADMIN', 'ADMIN1234'
GO
GO
CREATE PROC GET_PRODUCT
AS 
BEGIN
	SELECT MASP, TENSP, GIATIEN, DONVITINH, SOLUONGTON, TENKHO FROM dbo.SANPHAM, dbo.KHO WHERE dbo.SANPHAM.MAKHO = dbo.KHO.MAKHO

END
EXEC GET_PRODUCT

select EncryptedData = EncryptByPassPhrase('123', 'laptrinhvb.net' )
select EncryptedData = EncryptByPassPhrase('123', 'ADMIN1234' )
SELECT * FROM dbo.TAIKHOAN
UPDATE dbo.TAIKHOAN
SET MATKHAU = (select EncryptedData = EncryptByPassPhrase('123', 'ADMIN1234' ))
WHERE TAIKHOAN = 'ADMIN'

select convert(varchar(100),DecryptByPassPhrase('123', 0x02000000107A7025546B1299EA4C9BB78B6CDC13C7A214905A930AD07424825E17F3770D157A016CA78AD830EA4E41C4AD1BF8AF)) as giaima
FROM dbo.TAIKHOAN WHERE dbo.TAIKHOAN = 'admin'

INSERT INTO dbo.TAIKHOAN
(
    TAIKHOAN,
    MATKHAU,
    TENTAIKHOAN,
    MALOAI
)
VALUES
(   N'NGHIAXX', -- TAIKHOAN - nvarchar(50)
    EncryptByPassPhrase('123', 'ADMIN1234' ), -- MATKHAU - nvarchar(50)
    N'VAN NGHIA', -- TENTAIKHOAN - nvarchar(50)
    1    -- MALOAI - int
    )
GO

CREATE OR ALTER PROC INSERT_HOADON @MAHD VARCHAR(10), @MANV VARCHAR(10), 
@MAKH VARCHAR(10), @NGAYLAP DATE, @KHUYENMAI INT, @THANHTIEN MONEY
AS
BEGIN
	INSERT INTO dbo.HOADON
	(
	    MAHD,
	    MANV,
	    MAKH,
	    NGAYLAP,
	    THANHTIEN,
	    KHUYENMAI
	)
	VALUES
	(   @MAHD,        -- MAHD - varchar(10)
	    @MANV,        -- MANV - varchar(10)
	    @MAKH,        -- MAKH - varchar(10)
	    @NGAYLAP, -- NGAYLAP - date
	    @THANHTIEN,      -- THANHTIEN - money
	    @KHUYENMAI       -- KHUYENMAI - float
	    )
END
EXEC dbo.INSERT_HOADON @MAHD = 'HDA2A3',              -- varchar(10)
                       @MANV = 'NV01',              -- varchar(10)
                       @MAKH = 'KH01',              -- varchar(10)
                       @NGAYLAP = '2022-09-21', -- date
                       @KHUYENMAI = 10,          -- int
                       @THANHTIEN = 50000000      -- money


GO
CREATE PROC INSERT_GIOHANG @MAHD VARCHAR(10), @MASP VARCHAR(10), @SOLUONG INT, @GIABAN MONEY
AS
BEGIN
	INSERT INTO dbo.GIOHANG
	(
	    MAHD,
	    MASP,
	    SOLUONG,
	    GIABAN
	)
	VALUES
	(   @MAHD,  -- MAHD - varchar(10)
	    @MASP,  -- MASP - varchar(10)
	    @SOLUONG,   -- SOLUONG - int
	    @GIABAN -- GIABAN - money
	    )
END
GO