
-- TRIGGER CẬP NHẬT SỐ LƯỢNG TỒN KHI MUA HÀNG
GO
CREATE TRIGGER CAPNHATSLTON 
ON dbo.GIOHANG
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT
	SELECT @MASP = Inserted.MASP, @SOLUONG = Inserted.SOLUONG  FROM Inserted
	UPDATE dbo.SANPHAM 
	SET SOLUONGTON = SOLUONGTON - @SOLUONG
	WHERE dbo.SANPHAM.MASP = @MASP
END
GO
--UPDATE GIÁ BÁN GIỎ HÀNG
UPDATE dbo.GIOHANG 
SET GIABAN = SP.GIATIEN * SOLUONG
FROM dbo.SANPHAM SP
WHERE SP.MASP = dbo.GIOHANG.MASP
-- TRIGGER TÍNH GIÁ BÁN CỦA GIỎ HÀNG
CREATE OR ALTER TRIGGER CAL_GIABAN
ON dbo.GIOHANG
FOR INSERT
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT , @HOADON VARCHAR(10)
	SELECT @MASP = I.MASP, @SOLUONG = I.SOLUONG, @HOADON = I.MAHD FROM INSERTED I
	UPDATE dbo.GIOHANG
	SET GIABAN = @SOLUONG * SP.GIATIEN
	FROM SANPHAM SP
	WHERE SP.MASP = @MASP AND dbo.GIOHANG.MAHD = @HOADON AND GIOHANG.MASP = @MASP
END
GO
--- UPDATE TONG GIA SP CUA PHIEU GIAO HANG
UPDATE dbo.CTPGH
SET TONGTIEN = (SP.GIATIEN * SOLUONG)
FROM dbo.SANPHAM SP
WHERE SP.MASP = dbo.CTPGH.MASP

GO
-- TRIGGER CẬP NHẬT SỐ LƯỢNG KHI NHẬP HÀNG
CREATE TRIGGER UPDATE_NHAPHANG 
ON CTPGH
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @SOLUONG INT
	SELECT @MASP = I.MASP, @SOLUONG = I.SOLUONG FROM INSERTED I
	UPDATE dbo.SANPHAM
	SET SOLUONGTON = SOLUONGTON + @SOLUONG
	WHERE @MASP = dbo.SANPHAM.MASP
END

-- TRIGGER NHAP NHAT HAN SU DUNG CUA SAN PHAM KHI NHAP HANG
GO
CREATE TRIGGER UPDATE_HSD
ON dbo.CTPGH
FOR INSERT
AS
BEGIN
	DECLARE @MASP VARCHAR(10), @HANSUDUNG DATE
	SELECT @MASP = I.MASP, @HANSUDUNG = I.HANSUDUNG FROM Inserted I
	UPDATE dbo.SANPHAM
	SET HANSUDUNG = @HANSUDUNG
	WHERE @MASP = dbo.SANPHAM.MASP
END
ALTER TABLE dbo.PHIEUGIAOHANG ADD MAKHO VARCHAR(10) 
ALTER TABLE dbo.PHIEUGIAOHANG ADD CONSTRAINT MAKHO_CT FOREIGN KEY (MAKHO) REFERENCES dbo.KHO (MAKHO)
GO


---
CREATE PROC DELETE_SP @MASP VARCHAR(10)
AS
BEGIN
	DELETE FROM dbo.SANPHAM WHERE MASP = @MASP
END

EXEC dbo.DELETE_SP @MASP = 'SP20' -- varchar(10)
 
 DELETE FROM dbo.KHACHHANG WHERE MAKH = 'KH15'
 DELETE FROM dbo.TAIKHOAN WHERE TAIKHOAN = 'taikhoan1'

 ALTER TABLE dbo.HOADON
 ADD CONSTRAINT FK_KHHD
 FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH) ON DELETE SET NULL;