--- Proc xóa sản phẩm
CREATE PROC DELETE_SP @MASP VARCHAR(10)
AS
BEGIN
	DELETE FROM dbo.SANPHAM WHERE MASP = @MASP
END

EXEC dbo.DELETE_SP @MASP = 'SP20' -- varchar(10)
 
 DELETE FROM dbo.KHACHHANG WHERE MAKH = 'KH15'
 DELETE FROM dbo.TAIKHOAN WHERE TAIKHOAN = 'taikhoan1'

 ALTER TABLE dbo.HOADON
 ADD CONSTRAINT FK_KHHD
 FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH) ON DELETE SET NULL;

 -- Check valid Login
CREATE OR ALTER PROC CHECK_LOGIN @USERNAME NVARCHAR(50), @PASS NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 1)
		SELECT 1 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU = @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  AND MALOAI = 2)
		SELECT 2 AS CODE
	ELSE IF EXISTS(SELECT * FROM dbo.TAIKHOAN WHERE TAIKHOAN = @USERNAME AND MATKHAU != @PASS COLLATE SQL_Latin1_General_CP1_CS_AS  )
		SELECT 3 AS CODE
	ELSE
		SELECT 4 AS CODE
END

EXEC CHECK_LOGIN 'ADMIN', 'ADMIN1234'

-- Lấy sản phẩm
CREATE PROC GET_PRODUCT
AS 
BEGIN
	SELECT MASP, TENSP, GIATIEN, DONVITINH, SOLUONGTON, TENKHO FROM dbo.SANPHAM, dbo.KHO WHERE dbo.SANPHAM.MAKHO = dbo.KHO.MAKHO

END
EXEC GET_PRODUCT

----- Insert Hóa đơn 
CREATE OR ALTER PROC INSERT_HOADONByGioHang @MAHD VARCHAR(10), @MANV VARCHAR(10), 
@MAKH VARCHAR(10), @NGAYLAP DATE, @KHUYENMAI INT, @THANHTIEN MONEY
AS
BEGIN
	INSERT INTO dbo.HOADON
	(
	    MAHD,
	    MANV,
	    MAKH,
	    NGAYLAP,
	    THANHTIEN,
	    KHUYENMAI
	)
	VALUES
	(   @MAHD,        -- MAHD - varchar(10)
	    @MANV,        -- MANV - varchar(10)
	    @MAKH,        -- MAKH - varchar(10)
	    @NGAYLAP, -- NGAYLAP - date
	    @THANHTIEN,      -- THANHTIEN - money
	    @KHUYENMAI       -- KHUYENMAI - float
	    )
END
EXEC dbo.INSERT_HOADONByGioHang @MAHD = 'HDA34342A4',              -- varchar(10)
                       @MANV = 'NV01',              -- varchar(10)
                       @MAKH = 'KH01',              -- varchar(10)
                       @NGAYLAP = '', -- date
                       @KHUYENMAI = 10,          -- int
                       @THANHTIEN = 50000000      -- money

-- insert  Giỏ hàng
CREATE or alter PROC INSERT_GIOHANG @MAHD VARCHAR(10), @MASP VARCHAR(10), @SOLUONG INT
AS
BEGIN
	INSERT INTO dbo.GIOHANG
	(
	    MAHD,
	    MASP,
	    SOLUONG
	)
	VALUES
	(   @MAHD,  -- MAHD - varchar(10)
	    @MASP,  -- MASP - varchar(10)
	    @SOLUONG  -- SOLUONG - int
	    )
END

EXEC INSERT_GIOHANG '008F2FBK', 'SP03', 20
EXEC dbo.INSERT_GIOHANG @MAHD = 'HD11',    -- varchar(10)
                        @MASP = 'SP11',    -- varchar(10)
                        @SOLUONG = 10,  -- int
                        @GIABAN = 500000 -- money

GO
------ cập nhật trạng thái thanh toán
CREATE PROC UPDATE_TRANGTHAI @MAHD VARCHAR(10)
AS
BEGIN
	UPDATE dbo.HOADON SET TRANGTHAI = N'ĐÃ THANH TOÁN' WHERE MAHD = @MAHD

END
EXEC dbo.UPDATE_TRANGTHAI @MAHD = '5ZEGIG1N' -- varchar(10)
--
CREATE VIEW HD_KMAI
AS
SELECT HD.MAHD, HD.KHUYENMAI*HD.THANHTIEN KHUYENMAI				
FROM HOADON HD
SELECT * FROM HD_KMAI
---
SELECT SP.TENSP, SP.HANSUDUNG, GH.SOLUONG, GH.GIABAN, TENKH, SDT
FROM dbo.HOADON HD, dbo.SANPHAM SP, dbo.GIOHANG GH, KHACHHANG kh
WHERE HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP and hd.MAKH = kh.MAKH


-- THÔNG TIN HÓA ĐƠN BÁN HÀNG
GO
CREATE OR ALTER PROC GET_INF_INVOICE @MAHD VARCHAR(10)
AS
BEGIN
	SELECT SP.TENSP, SP.HANSUDUNG, GH.SOLUONG, GH.GIABAN,HD.MAHD,HD.KHUYENMAI, KH.TENKH, SDT, HD.THANHTIEN
	FROM dbo.HOADON HD, dbo.SANPHAM SP, dbo.GIOHANG GH, KHACHHANG KH
	WHERE HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP AND HD.MAHD = @MAHD AND KH.MAKH = HD.MAKH 
END
GO
EXEC GET_INF_INVOICE 'HD01'
--- update giaban giohang
UPDATE GIOHANG
SET GIABAN = SOLUONG * SP.GIATIEN
FROM SANPHAM SP
WHERE SP.MASP = GIOHANG.MASP 
--- UPDATE THANH TIEN HOA DON
UPDATE HOADON
SET THANHTIEN = (SELECT SUM(GIABAN) FROM GIOHANG GH WHERE GH.MAHD = HOADON.MAHD)
WHERE SP.MASP = GIOHANG.MASP 
--- THỐNG KÊ DOANH THU 
CREATE OR ALTER PROC TKDT_NAM
AS
BEGIN
SELECT SUM(THANHTIEN) DOANHTHU, MONTH(NGAYLAP) THANG
FROM dbo.HOADON 
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12
GROUP BY MONTH(NGAYLAP)
ORDER BY THANG
END
EXEC TKDT_NAM
--- data doanh thu khách hàng SP
CREATE OR ALTER PROC doanhThuData
AS
BEGIN
SELECT MONTH(NGAYLAP) THANG, SP.MASP, SP.TENSP, SUM(GH.SOLUONG) SOLUONGBAN ,SUM(GH.GIABAN) DOANHTHU
FROM dbo.HOADON HD, SANPHAM SP, GIOHANG GH
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12 AND HD.MAHD = GH.MAHD AND GH.MASP = SP.MASP
GROUP BY MONTH(NGAYLAP),SP.TENSP, SP.MASP
ORDER BY THANG
END
exec doanhThuData
--- TK SLUONG HÓA ĐƠN
CREATE OR ALTER PROC TKSLHD
AS
BEGIN
SELECT COUNT(*) SOLUONGHD, MONTH(NGAYLAP) THANG
FROM dbo.HOADON
WHERE MONTH(NGAYLAP) BETWEEN 1 AND 12
GROUP BY MONTH(NGAYLAP) 
END
EXEC TKSLHD
--- TK SAN PHAM
CREATE OR ALTER PROC TKSP
AS
BEGIN
SELECT SUM(GH.SOLUONG) TONGSOLUONG, SP.MASP
FROM SANPHAM SP, GIOHANG GH
WHERE GH.MASP = SP.MASP 
GROUP BY SP.MASP
END

EXEC TKSP
GO
--- LAY DANH MUC THEO TEN
CREATE or ALTER PROC GET_DANHMUC @TENDM NVARCHAR(100)
AS
BEGIN
	SELECT SP.MASP, SP.TENSP, SP.DONVITINH, SP.HANSUDUNG, SP.SOLUONGTON, SP.MAKHO, SP.MALOAI
	FROM SANPHAM SP, LOAISANPHAM L, DANHMUC DM
	WHERE SP.MALOAI = L.MALOAI AND L.MADM = DM.MADM AND DM.TENDANHMUC LIKE @TENDM
END

EXEC GET_DANHMUC N'Tăng cường miễn dịch'

select * from taikhoan


GO
CREATE PROC UPDATE_MK @MATKHAUMOI NVARCHAR(100), @EMAIL varchar(50)
AS
BEGIN
update TAIKHOAN 
set MATKHAU = @MATKHAUMOI
WHERE EMAIL = @EMAIL
END
GO
EXEC UPDATE_MK 'Nghia123', 'vantoan12@gmail.com'


ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ON DELETE CASCADE

ALTER TABLE GIOHANG ADD CONSTRAINT FK_HD_GH FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD) ON DELETE CASCADE


EXEC HIENTHI_CTHD 'HD01'
SELECT * FROM HOADON
CREATE PROC GETDATA_HD @MAHD VARCHAR(10)
AS
BEGIN
	SELECT TENKH, TENNV, NGAYLAP, THANHTIEN, HD.MAHD
	FROM HOADON HD, NHANVIEN NV, KHACHHANG KH
	WHERE HD.MANV = NV.MANV AND HD.MAKH = KH.MAKH AND HD.MAHD = @MAHD
END

EXEC TKDT_NAM 

-- TOP 5 KH CO SO HOA DON ...
CREATE PROC GET_TOP5KH 
AS
BEGIN
SELECT TOP 5 KH.MAKH, SUM (GH.GIABAN) DOANHTHU
FROM KHACHHANG KH, GIOHANG GH, HOADON HD
WHERE HD.MAHD = GH.MAHD AND HD.MAKH = KH.MAKH 
GROUP BY KH.MAKH
ORDER BY SUM(GH.GIABAN) DESC
END
